
name: debugger
env:
    TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: env
      run: |
        echo "CC=ccache clang -Qunused-arguments" >> $GITHUB_ENV
        echo "CXX=ccache clang++ -Qunused-arguments" >> $GITHUB_ENV
        echo "START_TIME=$(date '+%s')" >> $GITHUB_ENV
        mkdir -p "$PWD/run"
        echo "FLAG_STOP=$PWD/run/ninjaStop" >> $GITHUB_ENV

    - name: config push
      env:
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      if: ${{ env.PUSH_TOKEN != '' }}
      run: |
        echo "PUSH_TOKEN=${{ secrets.PUSH_TOKEN }}" >> $GITHUB_ENV
        git config --global user.email "aoeiuv020@gmail.com"
        git config --global user.name "AoEiuV020"

    - name: save prepare.sh
      run: |
        cat > ./script/prepare.sh <<EOF
        . ./script/download_ccache.sh
        . ./script/create_ccache_config.sh
        . ./script/maximize_build_space.sh
        . ./script/download_depot.sh
        . ./script/download_cipd.sh
        . ./script/src_prepare.sh
        EOF

    - name: keepalive
      run: |
        touch /tmp/keepalive
    - name: Setup Debug Session
      env:   
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: csexton/debugger-action@master

