
name: debugger
env:
    TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: env
      run: |
        echo "START_TIME=$(date '+%s')" >> $GITHUB_ENV
        echo "CC=ccache clang -Qunused-arguments" >> $GITHUB_ENV
        echo "CXX=ccache clang++ -Qunused-arguments" >> $GITHUB_ENV

    - name: push
      if: ${{ github.repository_owner == 'AoEiuV020' }}
      run: |
        echo "PUSH_TOKEN=${{ secrets.PUSH_TOKEN }}" >> $GITHUB_ENV
        git config --global user.email "aoeiuv020@gmail.com"
        git config --global user.name "AoEiuV020"

    - name: download ccache
      run: |
        git clone https://AoEiuV020:$PUSH_TOKEN@github.com/AoEiuV020/kiwibrowser-ccache-arm64.git $HOME/cache

    - name: Creating ccache configuration
      run: |
        mkdir -p $HOME/.ccache/
        echo 'compiler_check = none' >> $HOME/.ccache/ccache.conf
        echo "stats = false" >> $HOME/.ccache/ccache.conf
        echo 'max_size = 20G' >> $HOME/.ccache/ccache.conf
        echo "base_dir = $HOME" >> $HOME/.ccache/ccache.conf
        echo "cache_dir = $HOME/cache" >> $HOME/.ccache/ccache.conf
        echo "hash_dir = false" >> $HOME/.ccache/ccache.conf

    - name: Maximize build space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo swapoff -a
        sudo rm -f /mnt/swapfile

    - name: depot
      run: |
        git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export DEPOT_TOOLS_DIR=$PWD/depot_tools
        echo "$DEPOT_TOOLS_DIR" >> $GITHUB_PATH
        echo "$DEPOT_TOOLS_DIR/python2_bin" >> $GITHUB_PATH
        echo "$DEPOT_TOOLS_DIR/python_bin" >> $GITHUB_PATH

    - name: .cipd
      run: |
        echo .cipd
        git clone --depth 1 "https://github.com/kiwibrowser/dependencies" .cipd
        cp .cipd/.gclient .
        cp .cipd/.gclient_entries .

    - name: src
      run: |
        sudo apt-get update
        sudo apt-get install -y python openjdk-8-jdk-headless libncurses5 ccache
        sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
        git clone --depth 1 "https://github.com/kiwibrowser/src" src
        cd src
        curl "https://omahaproxy.appspot.com/all" | grep -Fi "android,stable" | cut -f3 -d"," | awk '{split($0,a,"."); print "MAJOR=" a[1] "\nMINOR=" a[2] "\nBUILD=" a[3] "\nPATCH=" a[4]}' > chrome/VERSION
        sudo bash install-build-deps.sh --no-chromeos-fonts
        build/linux/sysroot_scripts/install-sysroot.py --arch=i386
        build/linux/sysroot_scripts/install-sysroot.py --arch=amd64
        keytool -genkey -v -keystore keystore.jks -alias dev -keyalg RSA -keysize 2048 -validity 10000 -storepass public_password -keypass public_password -dname "cn=Kiwi Browser (unverified), ou=Actions, o=Kiwi Browser, c=GitHub"
        gclient runhooks
        mkdir -p out/arm64/
        cat .build/android_arm/args.gn | sed "s#target_cpu = \"arm\"#target_cpu = \"arm64\"#" | sed "s#android_default_version_name = \"Git\"#android_default_version_name = \"Git$(date '+%y%m%d')Gen${{ github.run_id }}\"#" > out/arm64/args.gn
        sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')2\"#" out/arm64/args.gn
        gn gen out/arm64/

    - name: keepalive
      run: |
        touch /tmp/keepalive
    - name: Setup Debug Session
      env:   
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: csexton/debugger-action@master

